### ISSUE TITLE
Ability to play nice with Dancer::Plugin::Passphrase

### ISSUE THREAD

**Issue by jjshoe** [LoonyPandora/Digest-Bcrypt#1]
Any chance you could take a hashref to new, allowing us to specify cost (and possibly other options)?

The next trick would be picking a 'default' cost to use in Digest.pm.

**Comment by genio** [comment]
@jjshoe would you mind closing this issue and opening it on the new repository, please?  https://github.com/genio/digest-bcrypt

I'll be maintaining the module from there from now on.

Thanks!

**Comment by jjshoe** [comment]
holy necro. I'll close, if you feel like making this module functional with the crypto times I'll let you re-create.

**Comment by genio** [comment]
Opened as https://github.com/genio/digest-bcrypt/issues/1

**Comment by genio** [comment]
@jjshoe The fix has been added.  I should publish it soon (as soon as I've completed some extra tests).
